source "https://rubygems.org"

ruby ">= 3.2"

gem "rails", "~> 7.2.0"
gem "pg", "~> 1.5"
gem "puma", ">= 6.4"
gem "rack-cors"
gem "bcrypt", "~> 3.1"
gem "tzinfo-data", platforms: %i[windows jruby]

group :development, :test do
  gem "debug", platforms: %i[mri windows], require: "debug/prelude"
  gem "rspec-rails", "~> 7.0"
  gem "factory_bot_rails"
end

group :development do
  gem "rubocop-rails-omakase", require: false
end
